<div class="pcontent">
<p><h2>Privacy Policy</h2></p>

<p>We value our community. You trust us with your information, and we&rsquo;re serious about that responsibility. We believe in transparency, and we&rsquo;re committed to being upfront about our privacy practices, including how we treat personal information we collect or receive. We know you care about your privacy, too, so we provide settings that allow you to control how certain information is used on BloomNation. This policy explains our privacy practices for BloomNation.com and services provided by Bloom Nation, LLC. (&ldquo;BloomNation&rdquo;).</p>

<p><h3>Information Collected or Received</h3></p>

<p>As a BloomNation member you are required to provide a valid email address at registration and choose a username or alias that may represent your identity on BloomNation</p>

<p>Depending on which services you choose to use, BloomNation may require additional information, such as a shop name, billing information (including billing address, phone number, credit card information), a mobile telephone number, a physical mailing address, and/or payment information. As a shop owner if you choose to enable direct payment, BloomNation may require information such as your bank account information and/or credit card information in order to verify your identity and provide this service to you.</p>

<p>You may optionally choose to provide your full name and other personal information (such as birthday, gender, location) to be publicly displayed in connection to your account and activity.</p>

<p>Your username, BloomNation ID or alias is publicly displayed and connected to your BloomNation activity. Other people may see your date joined, feedback, ratings, profile information, items listed for sale, shop pages, sold item listings, and comments in community spaces.</p>

<p>BloomNation automatically receives and records some information from your browser when you visit the site, such as your IP address, cookies and data about which pages you visit on the site through the use of log files provided by our third-party tracking-utility partners. This information helps us analyze and understand how the site works for members and visitors.</p>

<p>BloomNation uses the information described in this policy to provide and improve our services and products, for billing, for identification and authentication purposes, to contact members or interested parties, and for general research and aggregate reporting.</p>

<p>BloomNation&rsquo;s Terms of Use require all account owners to be at least 18 years of age (or have the permission and supervision of a responsible parent or legal guardian), therefore, this policy does not discuss use of our site or services by minors.</p>

<p><h3>Choice &amp; Control</h3></p>

<p>We know members of our community value having control over their own information, and therefore BloomNation gives you the choice of providing, editing or removing certain information, as well as choice over how we contact you.</p>

<p>You may change or correct your BloomNation account information (except your username) at any time. You may remove certain optional information you no longer wish to be publicly visible, such as your full name.</p>

<p>For various reasons, BloomNation may contact you about our services or your activity. Some of these messages are required, service-related messages for members.</p>

<p>If you no longer wish to use BloomNation&rsquo;s services or receive service-related messages, then you may close your account.</p>

<p><h3>Messages from BloomNation</h3></p>

<p>On occasion, BloomNation will send you messages. The default, required form of communication is email. In some situations, BloomNation may send you physical mail.</p>

<p>Some messages from BloomNation are service-related and required for members. Examples of service-related messages include, but are not limited to: a welcome/confirmation email when you register your account, notification of an order, or correspondence with BloomNation&rsquo;s support team. These messages are not promotional in nature. You may not opt-out of receiving service-related messages from BloomNation, unless you close your account.</p>

<p>As a member, BloomNation may also send you messages related to certain features on the site or your activity. BloomNation may also send you news or updates about changes to our site or services. By default, members will receive these messages via email.</p>

<p>BloomNation offers optional email newsletters. You must opt-in or subscribe to begin receiving newsletters, and subscription is available to both members and non-members. Members may subscribe or unsubscribe from optional newsletters under your account settings or by following the instructions contained in the newsletter emails. Non-members may subscribe by providing an email address, which will only be used by BloomNation for these newsletters. Non-members may unsubscribe from newsletters by following the instructions contained in the newsletter emails.</p>

<p><h3>Community</h3></p>

<p>BloomNation is both a marketplace and a community. Please use common sense and good judgement when posting in these community spaces or sharing your personal information with others on BloomNation. Be aware that any personal information you submit there can be read, collected, or used by others, or could be used to send you unsolicited messages. BloomNation generally does not remove content from community spaces, and your posts may remain public after your account is closed. You are responsible for the personal information you choose to post in community spaces on BloomNation.</p>

<p><h3>Information Sharing &amp; Disclosure</h3></p>

<p>BloomNation limits access to your personal information to employees who we believe reasonably need to come into contact with that information to provide products or services to you or in order to do their jobs.</p>

<p>As part of the buying and selling process, BloomNation will share information between the two members involved in the transaction. You may obtain another BloomNation member's email address, shipping address, payment information, and/or other information. As described in BloomNation's Terms of Use, you have a limited license to use this information only for BloomNation-related communications or for BloomNation-facilitated transactions. BloomNation has not granted you a license to use the information for unsolicited commercial messages. Without express consent from that person, you must not add any BloomNation member to your email or physical mailing list.</p>

<p>BloomNation may release your personal information to a third-party in order comply with a subpoena or other similar legal procedure, or when we believe in good faith that such disclosure is necessary to comply with the law; prevent imminent physical harm or financial loss; or investigate or take action regarding illegal activities, suspected fraud, or violations of BloomNation's Terms of Use. We may disclose personally identifiable information to parties in compliance with our Copyright and Intellectual Property Policy, as we in our sole discretion believe necessary or appropriate in connection with an investigation of fraud, intellectual property infringement, piracy, or other unlawful activity. In such events, BloomNation may disclose name, address, country, phone number, email address and company name.</p>

<p>BloomNation is affiliated with a variety of businesses and works closely with them. These businesses may offer promotions or sell items or services to you through BloomNation&rsquo;s services. BloomNation may also provide services or sell products jointly with affiliated businesses. Due to the nature of our business model, when an affiliated business is associated with your transaction, we may share information that is related to such transaction with that affiliated business. BloomNation may share aggregated demographic information with business partners.</p>

<p>BloomNation employs other companies and people to perform tasks on our behalf, and we need to share your information with them to provide products and services to you. Examples include but are not limited to fulfilling orders, processing payments, handling billing disputes and collections, analyzing data, providing marketing assistance and providing customer service. BloomNation may partner with third-party services for fraud prevention and/or identity verification.</p>

<p>In some cases, BloomNation may choose to buy or sell assets. In these types of transactions, member information is typically one of the business assets that is transferred. BloomNation will transfer information about you if BloomNation is acquired by or merged with another company. In this event, BloomNation will notify you by email or by putting a prominent notice on the site before information about you is transferred and becomes subject to a different privacy policy.</p>

<p>When you a load a page on BloomNation that has a social plug-in from a third-party site or service, such as a Like or Send button, you are also loading content from that third-party site. That site may request cookies directly from your browser. These interactions are subject to the privacy policy of the third-party site.</p>

<p>We can only speak for ourselves; this policy does not apply to the practices of third parties that BloomNation does not own or control, or individuals that BloomNation does not employ or manage. If you provide your information to others on BloomNation or throughout the Internet, different rules may apply to the use or disclosure of the information you provide to them. BloomNation does not control the privacy policies of third parties, and you are subject to the privacy policies of those third parties where applicable. BloomNation is not responsible for the privacy or security practices of other websites on the Internet, even those linked to or from the BloomNation site. We encourage you to ask questions before you disclose your personal information to others.</p>

<p><h3>Cookies &amp; Tracking Technologies</h3></p>

<p>BloomNation uses a variety of technologies to help us better understand how people use our site and services.</p>

<p>A cookie is a small data file sent from a web site to your browser that is stored on your computer's hard drive. BloomNation uses our own cookies for a number of purposes, including to access your information when you sign in; keep track of preferences you specify; display the most appropriate content based on your interests and activity on BloomNation; estimate and report BloomNation's total audience size and traffic; conduct research to improve our content and services. You can configure your browser's settings to reflect your preference to accept or reject cookies. If you reject all cookies, you will not be able to take full advantage of BloomNation's services.</p>

<p>We use Flash cookies (a.k.a local shared objects or LSOs) to store some of your viewing preferences on our site. Flash cookies are used to collect and store information, but differ from browser cookies in the amount, type and manner in which data is stored. BloomNation does not tie the information gathered by Flash cookies to your personally identifiable information.</p>

<p>BloomNation may partner with third-party services who may use various tracking technologies, such as browser cookies or Flash cookies, to provide certain services or features. These technologies allow a partner to recognize your computer each time you visit BloomNation, but do not allow access to personally identifiable information from BloomNation. BloomNation does not have access or control over these third-party technologies, and they are not covered by our privacy statement.</p>

<p><h3>Security</h3></p>

<p>The security of your personal information is important to us. Your BloomNation account information is protected by a password. It is important that you protect against unauthorized access of your account and information by choosing your password carefully, and keeping your password and computer secure by signing out after using our services. BloomNation encrypts sensitive information (such as credit card number) using secure socket layer technology (SSL). BloomNation follows generally accepted industry standards to protect the personal information submitted to us, both during transmission and once BloomNation receives it. No method of transmission over the Internet, or method of electronic storage, is 100% secure. Therefore, while we strive to use commercially acceptable means to protect your personal information, we cannot guarantee its absolute security.</p>

<p><h3>Data Retention</h3></p>

<p>BloomNation will retain your information for as long as your account is active or as needed to provide you services. If you no longer want BloomNation to use your information to provide you services, you may close your account. BloomNation will retain and use your information as necessary to comply with our legal obligations, resolve disputes, and enforce our agreements.</p>

<p><h3>Privacy Policy Changes</h3></p>

<p>BloomNation reserves the right to modify this privacy statement at any time, so please review it periodically. We&rsquo;ll communicate changes by posting a notice on the site. If we make material changes to this policy you will be notified here, by email, or other places BloomNation deems appropriate.</p>

<p><h3>Contact BloomNation</h3></p>

<p>If you have questions or suggestions you can contact BloomNation&rsquo;s support team by sending an email to legal@BloomNation.com, or writing to:</p>

<p>BloomNation Support Team - Privacy Policy<br />
8889 W. Olympic Blvd<br />
Beverly Hills, CA 90211</p>
</div>