<div class="pcontent">
<p><h2>Substitution Policy</h2></p>

<p>In some instances, the florists&rsquo; photo may represent an overall theme or look and include a one-of-a-kind vase which cannot be exactly replicated. Although the actual bouquet may not precisely match the photo, its temperament will. Occasionally, substitutions of flowers or containers happen due to weather, seasonality and market conditions which may affect availability. If this is the case with the gift you've selected, the local florist will ensure that the style, theme and color scheme of your arrangement is preserved and will only substitute items of equal or higher value.</p>
</div>