<?php $productList = $this->getProducts() ?>

<?php if(count($productList) > 0){ ?>
  <div class="vendor_prducts">
  	<h1 class="crossvendors">You May Also Be Interested In:</h1>
    <ul class="products-grid">
    	<?php foreach($productList as $_product){ ?>
      	<?php $dropship_vendor = $_product->getRandomVendor() ?>
				<li class="item">
          <a href="<?php echo $_product->getProductUrl()  ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->adaptiveResize(169,180); ?>" width="169" height="180" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
          <h2 class="product-name"><a href="<?php echo $_product->getProductUrl()  ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_product->getName() ?></a></h2>
					<?php if($_product->getRatingSummary()): ?>
          	<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
          <?php endif; ?>
          <div class="price-rate">
            <div class="price-box">
              <span class="regular-price" id="product-price-44">
                <span class="price">$<?php echo number_format($_product->getVendorPrice($dropship_vendor), 2)?></span>
              </span>
            </div>
            <div class="florist-rating">									
              <div class="rating-stars-back">			
                <div class="rating-stars-over" style="width:<?php echo $yelp_rating; ?>%"></div>                     
              </div>
            </div>    
          </div> 
          <div class="flourist-name"><?php echo $dropship_vendor->getVendorName(); ?></div>
        </li>
      <?php } ?>
    </ul>
	</div>
<?php } ?>