<head>
     <meta charset="utf-8" />
     <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
     <meta name="description" content="" />
     <meta name="author" content="" />

     <!-- Mobile meta (start) -->
     <meta name="HandheldFriendly" content="true"/>
     <meta name="MobileOptimized" content="320"/>
     <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=yes" />
     <meta http-equiv="cleartype" content="on" />
     <meta name="apple-mobile-web-app-capable" content="yes" />
     <!-- Mobile meta (end) -->

     <title>Sell your Flowers from your own Facebook Page!</title>

     <link rel="stylesheet" href="/js/facebook/css/reset.css" media="all" />
     <link rel="stylesheet" href="/js/facebook/fonts/fonts.css" media="all" />
     <link rel="stylesheet" href="/js/facebook/css/screen.css" media="all" />
     <link rel="stylesheet" href="/js/facebook/css/createAcc.css" media="all" />  	

     <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />

     <script src="/js/html5.js"></script>    
 
     <script src="/js/jquery/jquery-1.8.2.min.js"></script>
     <script>
         jQuery(document).ready(function($) {
             
             addToPage = function() {
                 // calling the API ...
                 var obj = {
                   method: 'pagetab',
                   redirect_uri: '<?= $this->getUrl('facebook/index/edit', array('_forced_secure'=>true))?>',
                 };
                 // Call the facebook
                 FB.ui(obj, function(response) {
                     if(response) {
                         $.each(response.tabs_added, function(pageid) {
                                 // Update bloomnation platform with facebook page info
                                 var url = '<?= $this->getUrl('udropship/vendor/facebook', array('_forced_secure'=>true));?>';
                                 var data = {facebook_page: ' ', facebook_page_id: pageid, dupdate: 'yes'};
                                 // Send the request
                                 $.post(url, data, function(response) {
                                     if(response.success) {
                                         window.top.location.href = '//www.facebook.com/pages/facebook/'+pageid+'?sk=app_'+appId;
                                     } else {
                                         alert(response.msg);
                                     }
                                 }, 'json');
                         });
                     }
                 });
             };
            
            /* Login in ajax mode
             *
             * @param string data -- data to signup
             * @param function onSuccess -- call this function upon succesful login
             *
             * return void
             */
            ajaxFloristLogin = function(username, password, onSuccess) {
                var url = '<?= $this->getUrl('udropship/vendor/index', array('_forced_secure'=>true))?>';
                var data = {'login[username]': username, 'login[password]': password};
                
                $.post(url, data, function(response) {
                    if(response.success) {
                        onSuccess();
                    } else {
                        alert('Incorrect user name or password');
                    }
                }, 'json');
            };

            /* Signup Login and Open facebook store in ajax mode
             *
             * @param string data -- data to signup
             * @param function onSuccess -- call this function upon succesful login
             *
             * return void
             */
            ajaxFloristSignup = function(data, onSuccess) {
                var url = '<?= $this->getUrl('udropship/vendor/index', array('_forced_secure'=>true))?>';
                
                $.post(url, data, function(response) {
                    if(response.success) {
                        onSuccess();
                    } else {
                        alert('Signup error');
                    }
                }, 'json');
            };
            
            //                                                    --------------- DOM ------------------
            // Plain install app button (user is already logged in)
            $('#installAppBtn').click(function() {
                addToPage();
                return false;
            });
            
            // Login and install button
            $('#loginBtn').click(function() {
                ajaxFloristLogin($('#f-username').val(), $('#f-sign__password').val(), function() {
                    addToPage();
                });
                return false;
            });
            
            // Signup and install button
            $('#regBtn').click(function() {
                var data = $('#signUp').serialize();
                
                ajaxFloristSignup(data, function() {
                    addToPage();
                });
                return false;
            });            
         });
     </script>
 </head>