<?php
 /**
 * GoMage Advanced Navigation Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2011 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 2.2
 * @since        Class available since Release 2.0
 */

/**
 * Top menu for store
 *
 * @see GoMage_Navigation_Block_Navigation
 */
?>

<?php $_menu = $this->renderCategoriesMenuHtml(0,'level-top') ?>
<?php if($_menu): ?>
    <?php switch ($this->getTypeNavigation()):  
            case GoMage_Navigation_Model_Layer::FILTER_TYPE_DROPDOWN: ?>
              <div class="gan-wrapper gan-top">
                  <ul class="gan-dropdown-list">                  
                      <?php echo $_menu ?>          
                  </ul>
              </div>           
           <?php break; ?>           
           <?php case GoMage_Navigation_Model_Layer::FILTER_TYPE_PLAIN: ?>
              <div class="gan-wrapper gan-top">
                  <ul id="gan_nav_top" class="gan-plain-list">
                    <?php echo $_menu ?>
                  </ul>
              </div>     
           <?php break; ?> 
           <?php default: ?>
              <div class="nav-container">
                    <ul id="nav">
                        <?php echo $_menu ?>
                    </ul>
              </div>  
    <?php endswitch; ?>
<?php endif ?>
<div id="lastmenu_item">
<a class="level-top" href="<?php echo Mage::getUrl('checkout/cart'); ?>"><span class="navbutton">
		<?php 
            $count = Mage::helper('checkout/cart')->getSummaryCount();
			$total_price = $this->helper('checkout')->formatPrice(Mage::getSingleton('checkout/cart')->getQuote()->getGrandTotal()); 
            if( $count == 1 ) {
                $text = $this->__('My Cart $'.$total_price.' <span>(%s item)</span>', $count);
            } elseif( $count > 0 ) {
                $text = $this->__('My Cart $'.$total_price.' <span>(%s items)</span>', $count);
            } else {
                $text = $this->__('My Cart $0.00 <span>(0 items)</span>' );
            }
            echo $text;
        ?></span></a>
</div>		
