<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <!-- Mobile meta (start) -->
        <meta name="HandheldFriendly" content="true"/>
        <meta name="MobileOptimized" content="320"/>
        <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=yes" />
        <meta http-equiv="cleartype" content="on" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <!-- Mobile meta (end) -->
        <?php
            if(Mage::getSingleton('udropship/session')->isLoggedIn()) {
                // Set title for florist interface
                $title = $this->getLayout()->getBlock('head')->getTitle($title);                
                $title = str_replace('%florist_name%',
                                                Mage::getSingleton('udropship/session')->getVendor()->getVendorName(),
                                                $title);
            } else {
                $title = 'Florist Interface';
            }
            
            $this->getLayout()->getBlock('head')->setTitle($title);
        ?>
        <?php echo $this->getChildHtml('head') ?>

        <script type="text/javascript">
          var __lc = {};
          __lc.license = 1088251;
          __lc.skill = 2;
        
          (function() {
            var lc = document.createElement('script'); lc.type = 'text/javascript'; lc.async = true;
            lc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.livechatinc.com/tracking.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(lc, s);
          })();
        </script>
        
        <script>
            (function() {
                    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ga);
            })();
            
             var _gaq = _gaq || [];
            
            _gaq.push(['_setAccount', 'UA-19515524-1']);
            _gaq.push(['_trackPageview']);
        </script>
    </head>
    <!-- ClickTale Top part -->
    <script type="text/javascript">
    var WRInitTime=(new Date()).getTime();
    </script>
    <!-- ClickTale end of Top part -->    
    <body <?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
    
        <?php echo $this->getChildHtml('after_body_start') ?>
        
        <div id="wrapper">
            <?php echo $this->getChildHtml('header') ?>
            
            <?php echo $this->getChildHtml('content') ?>
        </div>
        <?php echo $this->getChildHtml('footer') ?>
        
        <?php echo $this->getChildHtml('before_body_end') ?>
        
        <?php echo $this->getAbsoluteFooter() ?>
    </body>
    <!-- ClickTale Bottom part -->
    <div id="ClickTaleDiv" style="display: none;"></div>
    <script type='text/javascript'>
    document.write(unescape("%3Cscript%20src='"+
     (document.location.protocol=='https:'?
      'https://clicktale.pantherssl.com/':
      'http://s.clicktale.net/')+
     "WRc9.js'%20type='text/javascript'%3E%3C/script%3E"));
    </script>
    <script type="text/javascript">
    var ClickTaleSSL=1;
    if(typeof ClickTale=='function') ClickTale(7723,1,"www09");
    </script>
    <!-- ClickTale end of Bottom part -->
</html>
