<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
    
		$imageResizeWidth = Mage::getStoreConfig('smdesign_colorswatch/zoom/container_width')*Mage::getStoreConfig('smdesign_colorswatch/zoom/zoom_ratio');
		$imageResizeHeight = Mage::getStoreConfig('smdesign_colorswatch/zoom/container_height')*Mage::getStoreConfig('smdesign_colorswatch/zoom/zoom_ratio');
?>
<?php /* if ($_product->getImage() != 'no_selection' && $_product->getImage()): */?>
<p class="product-image product-image-zoom" <?php if (Mage::getStoreConfig('smdesign_colorswatch/zoom/image_size_type') == 2) : echo "style=\"width:".Mage::getStoreConfig('smdesign_colorswatch/zoom/container_width')."px; height:".Mage::getStoreConfig('smdesign_colorswatch/zoom/container_height')."px;\""; endif; ?>>
    <?php
        $_img = '<img id="image" src="';
        if (Mage::getStoreConfig('smdesign_colorswatch/zoom/image_size_type') == 2) {
        	$_img .= $this->helper('catalog/image')->init($_product, 'image')->resize($imageResizeWidth, $imageResizeHeight);
        } else {
        	$_img .= $this->helper('catalog/image')->init($_product, 'image');
        }
        
        $_img .= '" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</p>


<script type="text/javascript">
//<![CDATA[
SMDesignColorswatchPreloader.showPerload($('image'));<?php /* we need this line to show perload immediately and will be removed by callback onInitializationComplete */ ?>
Event.observe(window, 'load', function() {

	new SMDZoom('image', {
		errorReport: <?php echo (Mage::getStoreConfig('smdesign_colorswatch/zoom/show_info_error') ? 'true' : 'false')?>,
		width: <?php echo Mage::getStoreConfig('smdesign_colorswatch/zoom/width')?>,
		height: <?php echo Mage::getStoreConfig('smdesign_colorswatch/zoom/height')?>,
		offsetLeft: <?php echo Mage::getStoreConfig('smdesign_colorswatch/zoom/offset_left')?>,
		offsetTop: <?php echo Mage::getStoreConfig('smdesign_colorswatch/zoom/offset_top')?>,
		onclick: function(zoomClass) { },
		dblclick: function(zoomClass) { },
		onInitializationComplete: function() {
			SMDesignColorswatchPreloader.removePerload($('image'));
		},
<?php /* if you need extra css propert for zoom elements zoomerDivCss and wrapperDivCss will overwrite any zoom property */ ?>
//		wrapperBackgroundColor : '#F00',
//		zoomerDivCss : { opacity : .8, background : '#FFF' },
//		wrapperDivCss : { border: '1px solid blue' },
		startZoomEvent: function(zoomClass) {<?php /* this func is called near before element is append in html */ ?>
			/* example fade effect */
//      Element.setStyle(zoomClass.zoomWrapper, { opacity:0});
//    	zoomClass.zoomWrapper.fade({duration:0.5, from:.2, to:1});
			/* example grow effect - this example work with outside zoom only */
			if (!zoomClass.config.insideZoom) {
				Element.setStyle(zoomClass.zoomWrapper, { display:'none' });
	    	zoomClass.zoomWrapper.grow({duration: 0.5});
			} else {
	      Element.setStyle(zoomClass.zoomWrapper, { opacity:0});
	    	zoomClass.zoomWrapper.fade({duration:0.5, from:.2, to:1});
			}
		},
		insideZoom: <?php echo (Mage::getStoreConfig('smdesign_colorswatch/zoom/zoom_type') ? 'true' : 'false')?>,
		insideZoomFull: <?php echo (Mage::getStoreConfig('smdesign_colorswatch/zoom/zoom_type') == 2 ? 'true' : 'false')?>

	});
});
//]]>
</script>
<?php /* else: ?>
<p class="product-image">
    <?php
        $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(265).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</p>
<?php endif; */ ?>



<?php if (count($this->getGalleryImages()) > 0): ?>
<div class="more-views">
    <h2><?php echo $this->__('More Views') ?></h2>
    <ul>
    <?php foreach ($this->getGalleryImages() as $_image): ?>
        <li>
            <a href="#" onclick="<?php if (Mage::getStoreConfig('smdesign_colorswatch/zoom/more_view_change_main_image')) : ?> SMDesignColorswatchPreloader.showPerload($('image')); $('image').src = '<?php 
		        if (Mage::getStoreConfig('smdesign_colorswatch/zoom/image_size_type') == 2) :
            echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($imageResizeWidth, $imageResizeHeight)	; 
            else :
            echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()); 
            endif;
            ?>?rand=' + Math.random();<?php else : ?> popWin('<?php echo $this->getGalleryUrl($_image) ?>', 'gallery', 'width=300,height=300,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes'); <?php endif; ?>return false;" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(56); ?>" width="56" height="56" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" /></a>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>