<?php
/**
 * Unirgy_NotifyVendor extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Unirgy
 * @package    Unirgy_NotifyVendor
 * @copyright  Copyright (c) 2008 Unirgy LLC
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * @category   Unirgy
 * @package    Unirgy_NotifyVendor
 * @author     Boris (Moshe) Gurevich <moshe@unirgy.com>
 */
?>
<ul>
<?php foreach ($this->getItems() as $_item): ?>
    <li>
        <?php echo $_item->getProduct()->getName() ?>
        <?php if ($_item->getQty()!=1) echo $this->__('x %s', $_item->getQty()*1) ?>
    </li>
<?php endforeach ?>
</ul>