<?php

?>
<!-- navigation BOF -->
<?php $_menu = $this->renderCategoriesMenuHtml(0, 'level-top', 'sub-wrapper' ) ?>
<?php if($_menu): ?>
<nav class="queldorei">
    <div class="nav-top-title"><div class="icon"><span></span><span></span><span></span></div><a href="#"><?php echo $this->__('Navigation'); ?></a></div>
    <ul id="queldoreiNav">
         <li class="level0 level-top">
         	<a href="<?php echo $this->getUrl(); ?>"><span><?php echo $this->__('Home'); ?></span></a>
         </li>
         <li class="level0 level-top">
         	<a href="/occasion.html"><span><?php echo $this->__('Shop Now'); ?></span></a>
         </li>	 
         <li class="level0 level-top">
         	<a href="/cms/index/aboutus"><span><?php echo $this->__('About Us'); ?></span></a>
         </li>
	 <!--
         <li class="level0 level-top">
         	<a href="/contact-us"><span><?php echo $this->__('Contact Us'); ?></span></a>
         </li>
         <li class="level0 level-top">
         	<a href="/events-info"><span><?php echo $this->__('Events'); ?></span></a>
         </li>
	 -->
    </ul>
</nav>
<?php endif ?>
<!-- navigation EOF -->