<?php
 /**
 * GoMage Advanced Navigation Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2011 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 2.2
 * @since        Class available since Release 1.0
 */
?>
<?php if($this->canShowBlock()): ?>
<div class="block block-layered-nav gomage-navigation-slider-type-<?php echo $this->getSliderType();?> gomage-navigation-icons-<?php echo $this->getIconStyle();?>">
    <div class="block-title">
        <strong><span><?php echo $this->__('Flower Finder') ?></span></strong>
    </div>



    <div class="block-content">
        <?php echo $this->getStateHtml() ?>
        <?php if($this->canShowOptions()): ?>
            <p class="block-subtitle">


    			<?php if(count($this->getActiveFilters()) > 0):?>
    				<?php if (Mage::helper('gomage_navigation')->isGomageNavigationAjax()): ?>
    					<button class="button" onclick="setNavigationUrl('<?php echo urlencode($this->getClearUrl(true));?>'); return false;"><span><span><?php echo $this->__('Clear All') ?></span></span></button>
    				<?php else: ?>
    					<button class="button" onclick="setLocation('<?php echo $this->getClearUrl();?>')"><span><span><?php echo $this->__('Clear All') ?></span></span></button>
    				<?php endif; ?>

    			<?php endif;?>
    		</p>
            <dl id="narrow-by-list">
            	<?php
            	$ccId = Mage::registry('current_category')->getParentId();
            	if($ccId != 20){
            		echo $this->getLayout()->createBlock('core/template')->setTemplate('impl_custom/left_categories.phtml')->toHtml();
            	}
            	?>

                <?php $_filters = $this->getFilters(); ?>
                <?php foreach ($_filters as $_filter):
				if($ccId == 20 || ($_filter->_filter->getRequestVar() != 'occasions' && $ccId != 20)){
                	$filter_id = 'advancednavigation-filter-content-'.$_filter->_filter->getRequestVar();

                ?>


                <?php if($_filter->getItemsCount()): ?>

                    <?php if($_filter->canShowPopup()):?>

                        <?php $note_content = trim($_filter->getPopupText())?>

    					<?php if(strlen($note_content)):?>
    						<?php

    	                    		$styles = '';

    	                    		if($content_width = $_filter->getPopupWidth()){

    	                    			$styles .= "width:{$content_width}px;";

    	                    		}
    	                    		if($content_height = $_filter->getPopupHeight()){

    	                    			$styles .= "height:{$content_height}px;";

    	                    		}

    	                    	?>

    	                    	<dd id="filter-<?php echo $_filter->getPopupId();?>-note-content" class="filter-note-content" <?php if($styles):?> style="<?php echo $styles;?>" <?php endif;?>>
    								<?php echo nl2br($note_content);?>
    	                    	</dd>
    					<?php endif;?>
					<?php endif;?>

                    <dt onclick="navigationOpenFilter('<?php echo $_filter->_filter->getRequestVar();?>');">
                    	<span class="filter-name"><?php echo $this->__($_filter->getName()) ?></span>

                    	<?php if($_filter->canShowPopup()):?>

	                    	<?php if(strlen($note_content)):?>

	                    	<span class="filter-note-handle" onmouseout="hideNavigationNote();" onmouseover="showNavigationNote('filter-<?php echo $_filter->getPopupId();?>-note-content', this)">?</span>

	                    	<?php endif;?>

                    	<?php endif;?>
                    </dt>
                    <dd id="<?php echo $filter_id;?>" <?php if($_filter->canShowMinimized()){?> style="display:none;" <?php } ?> >

                    <?php if ($_filter->canShowResetFirler()): ?>
                        <?php $_filter_reset =  $this->getResetFirlerUrl($_filter, $_filter->ajaxEnabled()); ?>
                        <?php if ($_filter_reset): ?>
                             <a href="<?php echo $_filter_reset; ?>" <?php if ($_filter->ajaxEnabled()): ?>onclick="setNavigationUrl('<?php echo urlencode($_filter_reset); ?>'); return false;"<?php endif; ?> >Reset</a>
                        <?php endif; ?>
                    <?php endif; ?>


                    <?php echo $_filter->getHtml() ?>
					</dd>
                <?php endif; ?>
                <?php } ?>
                <?php endforeach; ?>
            </dl>
            <script type="text/javascript">
            	// <![CDATA[
            	decorateDataList('narrow-by-list');
            	// ]]>
            </script>
            <script type="text/javascript">
			jQuery(document).ready(function() {
			jQuery("#narrow-by-list dt:first-child").addClass("style-list");
			jQuery("#narrow-by-list dt:nth-child(2)").addClass("flower-list");
			jQuery("#narrow-by-list dt:last-child").addClass("color-list");
			jQuery("#narrow-by-list dd li:last-child a").addClass("last-child");
			})
			</script>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>
