<h2>Top florists by state</h2>
<hr/>
<br/>
<div class="sitemapInfo">
<?php
    $c = 0;
    $threshold = 10;
    $colNumber = 20;
    foreach($this->getFlorists() as $state): 
        if($c % $colNumber == 0 || $c == 0):?>
        <div class="col-list">
        <?php endif; ?>
        
        <div class="state">
            <div class="stateName"><?= $state->name?></div>
            <ul>
                <?php foreach($state->florists->florist as $florist):
                    if($florist->rating > $threshold):
                    $url = '/'.strtolower(str_replace(' ','-',
                                                      Mage::getModel('udropship/vendor')->load($florist->id)->getCity().'-'.
                                                      Mage::getModel('catalog/category')->load(Mage::helper('udropship')->getCategoryByVendor($florist->id)->getId())->getUrlKey()
                                )).'.html'; ?>
                    <li><a href="<?= $url;?>"><?=$florist->name;?></a></li>
                    <?php endif; ?>
                <?php endforeach;?>
            </ul>
        </div>
    
        <?php $c++; if($c % $colNumber == 0):?>
        </div>
        <?php endif; ?>
<?php endforeach; ?>
</div>