<?php
// Get init values
$val = explode(',',$this->getCurValue());
$name = $this->getAttrName();
// Get attribute values array
$attribute = Mage::getSingleton('eav/config')->getAttribute('catalog_product', $name);
$attrValues = $attribute->getSource()->getAllOptions(false);
?>

<select name="<?php echo $name?>[]" multiple="multiple" style="width: 150px; height: 250px;">
    <?php foreach($attrValues as $oVal):?>
    <option value="<?php echo $oVal['value'];?>" <?php echo (in_array($oVal['value'],$val)) ? 'selected="selected"' : '';?>><?php echo $oVal['label'];?></option>
    <?php endforeach; ?>
</select>

