<style type="text/css">
.udmulti-vendor-select, .udmulti-vendor-method { margin:3px; }
.udmulti-vendor-save { margin:10px; }
#udmulti-message span { padding:4px; }
#udmulti-message .success { background:#CFC; }
#udmulti-message .error { background:#FCC; }
</style>
<script type="text/javascript">

var vendors = <?php echo $this->getVendorsJson() ?>;

$$('.po-item-vendor').each(function (el) {
    var itemId = el.id.replace(/[^0-9]/g, ''), i, v
    var html = '<select name="udpo[vendors]['+itemId+'][id]" class="udmulti-vendor-select" id="udmulti-vendor-'+itemId+'">'
    $H(vendors[itemId].all).each(function (allV) {
        html += '<option value="'+allV.key+'" '
        html += allV.key==vendors[itemId].current ? 'selected="selected"' : ''
        html += '>'+allV.value.name+'</option>'
    })
    html += '</select>'
    html += '<input type="hidden" name="udpo[vendors]['+itemId+'][cost]" id="udmulti-vendor-'+itemId+'-cost" value="'+vendors[itemId].all[vendors[itemId].current].cost+'" />'
    el.update(html)
})

$$('.udmulti-vendor-select').each(function (el) {
    el.baseValue = el.value
    window.udpoFields.push(el)
    $(el).observe('change', function (e) {
        window.checkButtonsRelation()
        var itemId = el.id.replace(/[^0-9]/g, '')
        $(el.id+'-cost').value = vendors[itemId].all[el.value].cost
    })
})
</script>
