<?php

?>
<?php
// On IE 8 force IE 7 view on the checkout page, required because of numerous issues
$ie8 = false;
if(stripos($_SERVER['HTTP_USER_AGENT'],'MSIE 8')) {
  $ie8 = true;
}
if(stripos($_SERVER['HTTP_USER_AGENT'],'MSIE 9')) {
  $ie8 = true;
}

$module = $this->getRequest()->getModuleName();

$metaOverride = Mage::helper('urls')->getMetaOverride();
?>
<?php if('checkout'  == $module && $ie8):?>
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7">
<?php endif;?>
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<title>
<?php
  $override = Mage::helper('urls')->getTitleOverride();
  echo ($override) ?: $this->getTitle();
?>
</title>
<meta name="description" content="<?php echo htmlspecialchars($metaOverride) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>

<?php echo $this->getIncludes() ?>

